### ISSUE TITLE
Add run recovery

### ISSUE THREAD

**Issue by bbangert** [loads/loads-broker#20]
When loads is restarted, it should recover runs already running. This can be done in several parts, and should be done after all the existing allocated instances have been discovered and given to the AWSPool.
1. Query the database for all runs that are not finished
2. For each incomplete run:
   1. Load the run
   2. Start the RunManager with the loaded run

The RunManager currently has some code to handle skipping portions of the run's lifecycle, they are unverified in practice though. 

In theory the AWSPool will recover existing instances for a run, because every AWS instance is tagged to the uuid of a Step, so when a Step needs instances, the ones it asks for will be returned. The RunManager will need to know its recovering so it calls AWSPool's request_instances with `allocate_missing` set to False.

This will require extensive unit testing of various conditions with mock AWS instances.

**Comment by rpappalax** [comment]
When I relaunch loads-broker it 're-claims' existing instances, it seems that most of the time the broker stalls so I'm not sure the re-claim mechanism is working correctly.

**Comment by chartjes** [comment]
@rpappalax can you verify if this is still an issue?

**Comment by rpappalax** [comment]
@pjenvey  "In theory the AWSPool will recover existing instances for a run, because every AWS instance is tagged to the uuid of a Step."  This may work if the broker is left running and the db is left intact.  However, in the case where the broker is re-started (and the db deleted), there is no mechanism for the broker to re-claim instances.
