### ISSUE TITLE
Upgrade Grafana

### ISSUE THREAD

**Issue by pjenvey** [loads/loads-broker#85]
With an improved InfluxDB setup (#70) it looks like we'll need to upgrade Grafana. I don't think the old version we currently include supports the newer InfluxDB 0.9 REST API.

Grafana as of v2.0 now has its own required backend server (I think there's npm and go back there now) so it's no longer easily embeddable.

They do have a docker image, so we could potentially setup a Grafana instance per run. Their official image is pretty large though (260mb), which adds extra download time to already lengthy runs. There is an experimental alpine based image out there.

Additionally I couldn't get either image to work on our CoreOS instances -- everything appears ok but I get no HTTP response from it.

**Comment by pjenvey** [comment]
alpine images for reference:

https://github.com/grafana/grafana-docker/issues/44
https://hub.docker.com/r/adipirro852/grafana/

**Comment by rpappalax** [comment]
i can talk to ops at the test-infra mtg

**Comment by bbangert** [comment]
It's actually a bit worse than I thought after reviewing how Grafana now runs. Previously I did dynamic config file hackery based on the URL to tell Grafana to use the appropriate Influxdb database. With the new stand-alone app, it loads its INI file once, at startup, and it doesn't even store the database info in the INI file, it's stored in a sqlite db.

Since an entire Grafana instance is now pegged too a single database config loaded at start-up, the prior method of having one grafana for multiple test-runs is out-the-window I believe. We will instead need to do something like:

- Spin up test-run and InfluxDB
- Spin up Grafana instance
  - Configure Grafana instance to use appropriate InfluxDB (http://docs.grafana.org/http_api/data_source/#create-data-source)
  - Load saved dashboards into Grafana instance (http://docs.grafana.org/http_api/dashboard/#create-update-dashboard)

Then at the end, shut it all down, including the Grafana instance. When QA wants to review prior test-runs, we'll need a system that makes the Influx/Grafana instances, loads the influx db from S3, configures the Grafana, etc. all over again.
